### PR TITLE
Pause menu

### PR DESCRIPTION
**Pull request by Krutonium**
This PR adds a Pause Menu and an Options Window that can be opened with it. It needs artwork desperately.

I also as a side note, also added WASD to the default controls, and Alt+Enter and F11 both toggle a Borderless Fullscreen Experience.

### CODE REVIEW

**Comment by Krutonium** [comment]
https://cdn.discordapp.com/attachments/774508896710295573/802661756861808650/PauseMenu.PNG

**Comment by Krutonium** [comment]
@SuscipiamSingularitatem

**Review by HazmatDrone — CHANGES_REQUESTED** [review]
If this is going to be a closed-source game then it should not under any circumstances be given the Apache license. Also, this should've been in a separate PR.

**Comment by Krutonium** [comment]
> If this is going to be a closed-source game then it should not under any circumstances be given the Apache license. Also, this should've been in a separate PR.

https://stackoverflow.com/questions/21940298/can-i-use-a-font-under-apache-licence-2-0-in-a-commercially-distributed-game

**Review by HazmatDrone — APPROVED** [review]
My bad, I didn't see the file location

**Comment by SuscipiamSingularitatem** [comment]
If you're going to go to the effort, pick a nicer font maybe...

**Comment by HazmatDrone** [comment]
Press Start 2P is nice

**Pull request merged**
