### PR TITLE
Implement generic entities that all unique entities inherit from.

### PR DESCRIPTION
**Pull request by HazmatDrone**
The aim of this PR is to make generic entities, with all the basic generic properties required to function. Other, novel items can then build upon these, adding textures, animations, special behavior, etc. Then when we want to change the behavior of, say, all 

- [x] `GameCharacter : KinematicBody2D` (Generic character, e.g. player, NPC, enemy. Can walk around, hit walls, use weapons, get hurt, etc)
  * Sprite
  * Animation
  * Collision Box
  * Hitreg
  * Faction (to make certain GameCharacters behave in certain ways when they notice other GameCharacters of same/different faction)
- [x] `Item : RigidBody2D` (Generic item. Can be dropped in the world, added to inventories, held by GameCharacters.)
  * Sprite
  * Collision Box
- [ ] `MeleeWeapon : Item` (Generic stabby stabby. Can be used by GameCharacters to attack.)
  * Hitreg
  * Animation
  * Attack speed, damage, etc
- [x] `RailEntity : KinematicBody2D` (Generic rail object. Can travel along rails, collide with GameCharacters, be coupled with other rail entities, become derailed, etc)

### CODE REVIEW

**Comment by HazmatDrone** [comment]
@Krutonium should GameCharacters/RailEntities be items? It might be vaguely useful to think of every object in the game as an item that can be put into a menu, or inventory (even if a lot of them would only be visible as items in the level editor)

**Comment by Krutonium** [comment]
Yes, and it should be a bool that decides if they can be made into an item. Generic bases are good. Plus some modder will have lovely day when they can take an NPC, turn them into an item, grind them up, and make villager bread super easily.

**Comment by HazmatDrone** [comment]
This PR ends up restructuring a lot of stuff for the sake of cleanliness so expect a bunch of merge conflicts if you branched before this is merged

**Comment by HazmatDrone** [comment]
@SuscipiamSingularitatem  @Krutonium

**Comment by HazmatDrone** [comment]
I'll implement MeleeWeapon in a future PR.

**Pull request merged**
